name: Build and Test

on: [push, pull_request]

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build project
        run: make build

      - name: Run tests
        run: |
          for file in tests/*; do
            echo "Running test $file"
            make run ARGS="$file"
          done
