name: Build and Test

on: [push, pull_request]

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind

      - name: Build project
        run: cd jlox && make build

      - name: Run tests
        run: |
          cd jlox && make test

      - name: Additional tests
        run: |
          cd clox
          make
          valgrind --leak-check=full ./build/clox
